
clustering_framework: cc
project_name: deep_clustering
group: imagenet_dogs
run_name: CC
dataset: imagenet_dogs
dataset_path: "./data_folder/imagenet_dogs"

backbone: resnet34
proj_dim: 128

optimizer: adam
lr: 0.0003
weight_decay: 0.

epochs: 1000
eval_interval: 10
crop_size: 224
batch_size: 256

clusters: 15
clusterings: 1
